// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSubdirectory(arg1) {
  return window['go']['main']['App']['GetSubdirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
